# Your Name or Company
title: ERPware

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: ERPware, bir işletmenin tüm departmanlarında ve iş süreçlerinde mevcut yazılımlarla entegre çalışan çözümler sunar. Bu çözümler, finansal yönetim, insan kaynakları yönetimi, üretim, envanter yönetimi, satış ve pazarlama gibi işletme süreçlerinin tamamını yönetmeye yardımcı olur. ERPware, işletmelerin daha verimli, organize ve veriye dayalı kararlar almasına olanak tanır.
# Add your social links
# social:
#  - platform: github
#    url: https://github.com/brianmaierjr
#  - platform: facebook
#    url: https://facebook.com/brianmaierjr
#  - platform: twitter
#    url: https://twitter.com/brianmaierjr
#  - platform: linkedin
#    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
